#ifndef __LLCLIENTERRORS_H__
#define __LLCLIENTERRORS_H__

// Unique error codes to LLClient
#define LLCLIENT_SUCCESS								 0
#define LLCLIENT_BAD_PARAMS								-10
#define LLCLIENT_WRONG_NUM_PUB_OBJECTS					-11
#define LLCLIENT_PUBCERT_FOUND_PROBLEM					-12
#define LLCLIENT_SIG_SIZE								-13
#define LLCLIENT_CERT_SIZE								-14
#define LLCLIENT_EXTENDED_AUTH_PROBLEM					-15
#define LLCLIENT_BAD_HASH_LEN							-16
#define LLCLIENT_OBJECT_NOT_FOUND						-17
#define LLCLIENT_CONTEXT_IS_NULL						-18
#define LLCLIENT_PRIVATE_NOT_FOUND						-19
#define LLCLIENT_UNKNOWN_HANDLE							-20
#define LLCLIENT_PARAMETER_LENGTH						-21
#define LLCLIENT_SIGNING_WITH_DATA_OBJ_NOT_ALLOWED		-22
#define LLCLIENT_UNKNOWN_OBJECT_TYPE					-23
#define LLCLIENT_ERR_FAILED_TO_INIT_LOAD_MODULE			-24
#define LLCLIENT_ERR_FAILED_TO_INIT						-25
#define LLCLIENT_ERR_LIB_IS_NOT_INITIALIZED				-26
#define LLCLIENT_ERR_FAILED_TO_INIT_REG_KEY				-27
#define LLCLIENT_ERR_MISSING_CRED						-28
#define LLCLIENT_NULL_PARAMETER_NOT_ALLOWED				-29
#define LLCLIENT_INSUFFICIENT_MEMORY					-30
#define LLCLIENT_INIT_SESSION_FAILED					-31
#define LLCLIENT_LOGON_FAILED							-32
#define LLCLIENT_OBJECTS_FIND_FAILED					-33
#define LLCLIENT_OBJECTS_INIT_FAILED					-34
#define LLCLIENT_FAILED_TO_GET_OBJECT					-35
#define LLCLIENT_FAILED_TO_SIGN							-36
#define LLCLIENT_FAILED_RELEASE_HANDLE					-37
#define LLCLIENT_FAILED_RELEASE_CONTEXT					-38
#define LLCLIENT_FAILED_TO_DEL_OBJECT					-39
#define LLCLIENT_FAILED_TO_GET_SERVER_INFO				-40
#define LLCLIENT_NO_MORE_ITEMS							-41
#define LLCLIENT_ERR_USR_LOCKED							-42
#define LLCLIENT_ERR_USR_DISABLED						-43
#define LLCLIENT_ERR_USR_PASSWORD_EXPIRED				-44
#define LLCLIENT_ERR_USR_NOT_ACTIVATED					-45
#define LLCLIENT_ERR_USR_DIALOG_CANCEL					-46
#define LLCLIENT_FAILED_GENERATE_USR_TOKEN				-47
#define LLCLIENT_FAILED_CREATING_OBJECT					-48
#define LLCLIENT_OBJECT_TYPE_NOT_ALLOWED				-49
#define LLCLIENT_OPERATION_NOT_SUPPORTED				-50
#define LLCLIENT_BAD_CERTIFICATE						-51

#define LLCLIENT_OBJECT_ALREADY_EXIST					-53
#define LLCLIENT_NO_MATCHING_PUBLIC_KEY_FOUND			-54
#define LLCLIENT_GENERATE_RSA_KEY_PAIR_FAILED			-55
#define LLCLIENT_GUID_ERROR								-56
#define LLCLIENT_MAX_NUM_OF_KEY_PAIRS_REACHED			-57
#define LLCLIENT_MAX_NUM_OF_RSA_OBJ_REACHED				-58
#define LLCLIENT_MAX_NUM_OF_DATA_OBJ_REACHED			-59
#define LLCLIENT_FAILED_TO_FIND_SERVER_TO_CONNECT		-60
#define LLCLIENT_FAILED_TO_CHANGE_CREDENTIALS			-61
#endif

