#ifndef __SAPIUMCONSTS_H__
#define __SAPIUMCONSTS_H__

#define UM_OPAQUE_CONTEXT_LENGTH			1124
#define SAPIUM_GUID_LENGTH					40
#define	UM_ENUM_USERS_CONTEXT_LENGTH		33000
// user rights ('flags' for SAPIUMUserAdd SAPIUMUserUpdate SAPIUMUserSync, 'RightsMask' in SAPIUMUserInfoGet)
#define SAPIUM_USER_RIGHT_NORMAL							0x00000001
#define SAPIUM_USER_RIGHT_APPLIANCE_ADMIN					0x00000002
#define SAPIUM_USER_RIGHT_USER_ADMIN						0x00000004
#define SAPIUM_USER_RIGHT_USERS_ADMIN_FOR_NONE_DI_INST		0x00000008
#define SAPIUM_USER_RIGHT_GROUP_ADMIN                       0x00000100

#define SAPIUM_MAX_GROUP_NAME_LENGTH			128
#define SAPIUM_MAX_GROUP_ADDRESS_LENGTH			128
#define SAPIUM_PHONE_NUMBER_LENGTH				64
#define SAPIUM_COUNTRY_LEN						2
#define SAPIUM_MAX_DOMAIN_NAME_LENGTH			128
#define SAPIUM_MAX_ORGANIZATION_LENGTH			64
#define	SAPIUM_MAX_ORGANIZATIONAL_UNIT_LENGTH	32

#define SAPIUM_MAX_NUMBER_OF_GROUPS_IN_CONT		30
#define SAPIUM_MAX_USER_BLOB_LENGTH				20480
#define SAPIUM_MAX_SAML_ID_LEN					64
#define SAPIUM_MAX_CPS_OBJECT_ID_LENGTH			64
#define SAPIUM_MAX_CPS_URI_LENGTH				128
#define TOKEN_ID_MAX_LEN						50

// CA contstants - the following were copied from mobconst.h
#define SAPIUM_MAX_CA_NAME_LENGTH						128
#define SAPIUM_MAX_CA_USER_NAME_LENGTH					64
#define SAPIUM_MAX_CA_USER_PASSWORD_LENGTH				32
#define SAPIUM_MAX_CITY_LENGTH							64
#define SAPIUM_MAX_STATE_LENGTH							128
#define SAPIUM_MAX_EMAIL_LENGTH							128 
#define SAPIUM_MAX_LOCALITY_LENGTH						128
#define SAPIUM_CN_LENGTH								256
#define SAPIUM_MAX_AIA_PUBLICATION_LENGTH				128
// The following const were copied from mobadmin.h
#define SAPIUM_MY_MAX_AIA_PUBLICATION_LENGTH			SAPIUM_MAX_AIA_PUBLICATION_LENGTH*4 // the default value in AD is much longer than MAX_AIA_PUBLICATION_LENGTH that is defined in mobinstall
#define SAPIUM_MAX_CRL_PUBLICATION_LENGTH				128
// The following const were copied from mobadmin.h
#define SAPIUM_MY_MAX_CRL_PUBLICATION_LENGTH			SAPIUM_MAX_CRL_PUBLICATION_LENGTH*4 // the default value in AD is much longer than MAX_CDP_PUBLICATION_LENGTH that is defined in mobinstall
#define SAPIUM_MAX_SERVICE_CONNECTION_POINT_URL_LEN		512	// same as defined on SymantecCA.cpp and ChosenCA.cpp
#define SAPIUM_MAX_CERT_PROFILE_ID						256 // same as defined on SymantecCA.cpp
#define SAPIUM_CERT_SERIAL_NUMBER_LEN_UC				20
#define SAPIUM_CERT_SERIAL_NUMBER_LEN					(2*SAPIUM_CERT_SERIAL_NUMBER_LEN_UC+1)
#define SAPIUM_MAX_CA_ACCOUNT_NAME						256
#define SAPIUM_MAX_DESCRIPTION_LENGTH					128
#define	SAPIUM_MAX_CA_VERSION_LEN						50
#define SAPIUM_MAX_VALID_EMAIL_DOMAINS					1024
#define SAPIUM_MAX_NUMBER_OF_CA_IN_CONT					50 
#endif